# Generated by Django 3.0.5 on 2020-04-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmodel',
            options={'verbose_name': 'Nhan Vien'},
        ),
    ]
