# Generated by Django 3.0.5 on 2020-04-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200410_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'verbose_name': 'Phòng ban'},
        ),
    ]
